// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SpringBootCloneApp.Data;
using SpringBootCloneApp.Models;
using SpringBootCloneApp.Models.Enums;
using System;
using System.Collections.Generic;

#nullable disable

namespace SpringBootCloneApp.Data.Configurations
{
    public partial class AuthorityConfiguration : IEntityTypeConfiguration<Authority>
    {
        public void Configure(EntityTypeBuilder<Authority> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__authorit__6531B6F503340C2B");

            entity.ToTable("authority");

            entity.Property(e => e.Id).HasColumnName("auth_id");
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("auth_name")
                .IsRequired();

            entity.HasMany(x => x.Clients)
                .WithMany(x => x.Authorities)
                .UsingEntity<ClientAuthority>(
                    l => l.HasOne(x => x.Client).WithMany().HasForeignKey(x => x.UserId),                   
                    r=>  r.HasOne(x => x.Auth).WithMany().HasForeignKey(x => x.RoleId)                   
                );



            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Authority> entity);
    }
}
