// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SpringBootCloneApp.Data;
using SpringBootCloneApp.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace SpringBootCloneApp.Data.Configurations
{
    public partial class ClientFoodFavConfiguration : IEntityTypeConfiguration<ClientFoodFav>
    {
        public void Configure(EntityTypeBuilder<ClientFoodFav> entity)
        {
            entity.HasKey(e => new { e.ClientId, e.FoodId }).HasName("PK__client_f__2DD560F9F63CBDF2");

            entity.ToTable("client_food_fav");

            entity.Property(e => e.ClientId).HasColumnName("client_id");
            entity.Property(e => e.FoodId).HasColumnName("food_id");

            entity.HasOne(d => d.Client).WithMany(p => p.ClientFoodFavs)
                .HasForeignKey(d => d.ClientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK15cwpt18syey0o02qlcud1c1q");

            entity.HasOne(d => d.Food).WithMany(p => p.ClientFoodFavs)
                .HasForeignKey(d => d.FoodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKi8ucp5jby4ml3ssxbqljsgqr0");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClientFoodFav> entity);
    }
}
