// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SpringBootCloneApp.Data;
using SpringBootCloneApp.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace SpringBootCloneApp.Data.Configurations
{
    public partial class ClientAuthorityConfiguration : IEntityTypeConfiguration<ClientAuthority>
    {
        public void Configure(EntityTypeBuilder<ClientAuthority> entity)
        {
            entity.ToTable("client_authority");

            entity.HasKey(e => new { e.UserId, e.RoleId }).HasName("PK__client_a__F972BF4B7C561F2D");

            entity.Property(x => x.RoleId).HasColumnName("auth_id");
            entity.Property(x => x.UserId).HasColumnName("client_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClientAuthority> entity);
    }

/*    public class IdentityUserRoleConfiguration : IEntityTypeConfiguration<IdentityUserRole<long>>
    {
        public void Configure(EntityTypeBuilder<IdentityUserRole<long>> entity)
        {
            entity.HasKey(e => new { e.UserId, e.RoleId }).HasName("PK__client_a__F972BF4B7C561F2D");

            entity.Property(x => x.RoleId).HasColumnName("auth_id");
            entity.Property(x => x.UserId).HasColumnName("client_id");

            entity.ToTable("client_authority");

        }

    }*/


}
