// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using EFCorePostgres.Data;
using EFCorePostgres.Models;
using EFCorePostgres.Models.Enums;
using System;
using System.Collections.Generic;

#nullable disable

namespace EFCorePostgres.Data.Configurations
{
    public partial class FoodOrderConfiguration : IEntityTypeConfiguration<FoodOrder>
    {
        public void Configure(EntityTypeBuilder<FoodOrder> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__food_ord__3213E83F8AC7B3DD");

            entity.ToTable("food_order");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Address)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("address");
            entity.Property(e => e.ClientId).HasColumnName("client_id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");


            entity.OwnsOne(x=> x.LatLng)
                .Property(e => e.Lat)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("lat");

            entity.OwnsOne(x=> x.LatLng)
                .Property(e => e.Lng)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("lng");



            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.PaymentId)
                .HasMaxLength(255)
                .HasColumnName("payment_id");
            entity.Property(e => e.Status)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.TotalPrice).HasColumnName("total_price");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            entity.HasOne(d => d.Client).WithMany(p => p.FoodOrders)
                .HasForeignKey(d => d.ClientId)
                .HasConstraintName("FKeeqknj22y8xo7k7qex47m9njn");

            entity.Property(x => x.Status)
                .HasConversion(
                    v => v.ToString(),
                    v => (OrderStatus)Enum.Parse(typeof(OrderStatus), v)
                );

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FoodOrder> entity);
    }
}
