// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using EFCorePostgres.Data;
using EFCorePostgres.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace EFCorePostgres.Data.Configurations
{
    public partial class FoodOriginConfiguration : IEntityTypeConfiguration<FoodOrigin>
    {
        public void Configure(EntityTypeBuilder<FoodOrigin> entity)
        {
            entity.HasKey(x => new { x.FoodId, x.Origin });
            entity.ToTable("food_origins");


            entity.Property(e => e.FoodId).HasColumnName("food_id");
            entity.Property(e => e.Origin)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("origin");

            entity.HasOne(d => d.Food).WithMany()
                .HasForeignKey(d => d.FoodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKb7xuhj95rkfmcpm3pnqcysdxa");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FoodOrigin> entity);
    }
}
