// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SpringBootCloneApp.Data;
using SpringBootCloneApp.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace SpringBootCloneApp.Data.Configurations
{
    /*public partial class RefreshTokenConfiguration : IEntityTypeConfiguration<RefreshToken>
    {
        public void Configure(EntityTypeBuilder<RefreshToken> entity)
        {
            entity.ToTable("refresh_token");

            entity.HasKey(e => new { e.UserId, e.LoginProvider, e.Name });

            entity.HasIndex(e => e.UserId, "UK_d3c7u4smwdgq9go1v08py5e87")
                .IsUnique()
                .HasFilter("([client_id] IS NOT NULL)");


            entity.Property(e => e.UserId).HasColumnName("client_id");
            entity.Property(e => e.ExpiryDate)
                .HasPrecision(6)
                .HasColumnName("expiry_date");

            entity.HasIndex(x => x.Value).IsUnique();

            entity.Property(e => e.Value)
                .HasColumnType("varchar(255)")
                .IsRequired(false);

            entity.Property(x => x.Name)
                .HasColumnName("Name")
                .HasColumnType("varchar(255)")
                .HasDefaultValue("");

            *//*entity.HasOne(d => d.Client).WithOne(p => p.RefreshToken)
                .HasForeignKey<RefreshToken>(d => d.UserId)
                .HasConstraintName("FKb1m0ci5xv6cfxpeafdqtq0drc");*//*


            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RefreshToken> entity);
    }*/

/*    public class IdentityUserTokenConfiguration : IEntityTypeConfiguration<IdentityUserToken<long>>
    {
        public void Configure(EntityTypeBuilder<IdentityUserToken<long>> entity)
        {
            entity.ToTable("refresh_token");


        }
    }*/
}
