// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using EFCorePostgres.Data.Configurations;
using EFCorePostgres.Models;
using System;
using System.Collections.Generic;
using Microsoft.Extensions.Configuration;
#nullable enable

namespace EFCorePostgres.Data;

public partial class AppDbContext : IdentityDbContext<Client, Authority, long, IdentityUserClaim<long>, ClientAuthority, IdentityUserLogin<long>, IdentityRoleClaim<long>, IdentityUserToken<long>>
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }


    public virtual DbSet<Authority> Authorities { get; set; }

    public virtual DbSet<Client> Clients { get; set; }

    public virtual DbSet<ClientAuthority> ClientAuthorities { get; set; }

    public virtual DbSet<ClientFoodFav> ClientFoodFavs { get; set; }

    public virtual DbSet<Food> Foods { get; set; }

    public virtual DbSet<FoodOrder> FoodOrders { get; set; }

    public virtual DbSet<FoodOrigin> FoodOrigins { get; set; }

    public virtual DbSet<FoodTag> FoodTags { get; set; }

    public virtual DbSet<OrderItem> OrderItems { get; set; }

    //public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.ApplyConfigurationsFromAssembly(typeof(AppDbContext).Assembly);

        OnModelCreatingPartial(modelBuilder);
    }  

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);


}
