// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace SpringBootCloneApp.Models;

public partial class ClientAuthority : IdentityUserRole<long>
{
    public override long UserId { get; set; }

    public override long RoleId { get; set; }

    public virtual Authority Auth { get; set; } = null!;

    public virtual Client Client { get; set; } = null!;


    public override bool Equals(object? obj)
    {
       var other = obj as ClientAuthority;
        if (other == null) return false;
        return other.UserId == this.UserId && other.RoleId == this.RoleId;
    }

    public override int GetHashCode()
    {
        int hash = 13;
        hash = (hash * 7) + UserId.GetHashCode();
        hash = (hash * 7) + RoleId.GetHashCode();
        return hash;
    }
}