// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EFCorePostgres.Models;

public partial class Food
{
    public long Id { get; set; }

    public string CookTime { get; set; } = null!;

    public bool Hidden { get; set; }

    public string ImageUrl { get; set; } = null!;

    public string Name { get; set; } = null!;

    public double Price { get; set; }

    public virtual ICollection<ClientFoodFav> ClientFoodFavs { get; set; } = new List<ClientFoodFav>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}