// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using SpringBootCloneApp.Models.Enums;
using System;
using System.Collections.Generic;

namespace SpringBootCloneApp.Models;

public partial class FoodOrder
{
    public long Id { get; set; }

    public string? Address { get; set; }

    public LatLng? LatLng { get; set; }

    public DateOnly CreatedAt { get; set; }

    public string Name { get; set; } = null!;

    public OrderStatus Status { get; set; } 

    public double TotalPrice { get; set; }

    public DateOnly? UpdatedAt { get; set; }

    public long ClientId { get; set; }

    public string? PaymentId { get; set; }

    public virtual Client Client { get; set; } = null!;

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    /*public override string ToString()
    {
        return $"Id: {Id}, " +
          $"Address: {(Address ?? "null")}, " +
*//*          $"Lat: {(Lat ?? "null")}, " +
          $"Lng: {(Lng ?? "null")}, " +*//*
          $"LatLng: {LatLng}" +
          $"CreatedAt: {(CreatedAt.HasValue ? CreatedAt.Value.ToString("yyyy-MM-dd") : "null")}\n " +
          $"Name: {(Name ?? "null")}, " +
          $"Status: {(Status ?? "null")}, " +
          $"TotalPrice: {TotalPrice}, " +
          $"UpdatedAt: {(UpdatedAt.HasValue ? UpdatedAt.Value.ToString("yyyy-MM-dd") : "null")}, " +
          $"ClientId: {(ClientId.HasValue ? ClientId.Value.ToString() : "null")}";
    }*/
    
}