// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using SpringBootCloneApp.Models.DTOs;
using System;
using System.Collections.Generic;

namespace SpringBootCloneApp.Models;

public partial class Food
{
    public long Id { get; set; }

    public string CookTime { get; set; } = null!;

    public bool Hidden { get; set; }

    public string ImageUrl { get; set; } = null!;

    public string Name { get; set; } = null!;

    public double Price { get; set; }

    public virtual ICollection<FoodTag> FoodTags { get; set; } = new List<FoodTag>();
    public virtual ICollection<FoodOrigin> FoodOrigins { get; set; } = new List<FoodOrigin>();

    public virtual ICollection<ClientFoodFav> ClientFoodFavs { get; set; } = new List<ClientFoodFav>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();


    public void UpdateFromDTO(FoodDTO foodDTO)
    {
        var foodTags = foodDTO.FoodTags.Select(tag => new FoodTag()
        {
            Tag = tag
        }).ToList();


        var foodOrigins = foodDTO.FoodOrigins.Select(origin => new FoodOrigin()
        {
            Origin = origin
        }).ToList();

        this.CookTime = foodDTO.CookTime;
        this.FoodTags = foodTags;
        this.FoodOrigins = foodOrigins;
        this.Hidden = foodDTO.Hidden;
        this.ImageUrl = foodDTO.ImageUrl;
        this.Name = foodDTO.Name;
        this.Price = foodDTO.Price.Value;
    }

}