// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SpringBootCloneApp.Models;

public partial class OrderItem
{
    public long Id { get; set; }

    public double Price { get; set; }

    public int Quantity { get; set; }

    public long FoodId { get; set; }

    public long OrderId { get; set; }

    public virtual Food Food { get; set; } = null!;

    public virtual FoodOrder Order { get; set; } = null!;
}